server:
  port: ${PORT:8800}
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port:8761}/eureka/
 
spring:
  jackson:
    default-property-inclusion: non_null


info:
  app:
    java:
      target: "@maven.compiler.target@"
      source: "@maven.compiler.source@"
    scm:
        revision: "@buildNumber@"
        branch: "@scmBranch@"
        timestamp: "@timestamp@"
  
